---
Upgrade:
  - hostname: NaaS-MM-1
    device_type: MM
    host: 10.17.84.220:4343

  - hostname: NaaS-VMC-1
    device_type: MD
    host: 10.17.84.221:4343


default_settings:
  AOS_Source:
    device_type: ftp
    ftp_host: 10.17.84.225
    ftp_username: admin
    ftp_password: admin123456
    ftp_path: /

  MM:
    image_file_name: ArubaOS_MM_8.5.0.10-FIPS_76207
    image_version: 8.5.0.10
    image_build: "76207"
    upgrade_disk: Auto
    CheckList:
      - show: show clock


  MD:
    image_file_name: ArubaOS_VMC_8.5.0.10-FIPS_76207
    image_version: 8.5.0.10
    image_build: "76207"
    upgrade_disk: Auto
    Pre_image_AP: True
    max_ap_image_load: 1
    CheckList:
      - show: show clock

  Authentication:
    username: admin
    password: Aruba@123$


  Validate_Image_before_upgrade: False
  Validate_controller_sync_before_upgrade: False
  Validate_controller_up_before_upgrade: False

