---
Upgrade:
  - hostname: NaaS-MM-1
    type: MM
    #image_file_name: ArubaOS_MM_8.5.0.9-FIPS_75468
    #image_file_name: ArubaOS_MM_8.6.0.5-FIPS_75980
    image_file_name: ArubaOS_MM_8.7.0.0-FIPS_75916
    image_version: 8.7.0.0
    image_build: 75916
    host: 10.17.84.220:4343
    #disk: 0
    upload_type: local
  - hostname: NaaS-VMC-1
    type: MD
    #image_file_name: ArubaOS_VMC_8.5.0.9-FIPS_75468
    #image_file_name: ArubaOS_VMC_8.6.0.5-FIPS_75980
    image_file_name: ArubaOS_VMC_8.5.0.10-FIPS_76207
    image_version: 8.5.0.10
    image_build: 76207
    host: 10.17.84.221:4343
    #disk: 0
    upload_type: local

CheckList_MM:
  - show: show clock
  - show: show version
  - show: show image version
  - show: show storage
  - show: show cpuload
  - show: show memory
  - show: show boot
  - show: show switches
  - show: show switchinfo
  - show: show boot history

  - show: show crypto Ipsec sa
  - show: show master-redundancy
  - show: show database synchronize
  - show: show license
  - show: show running-config
  #- backup_flash: flashbackup
  #- copy_flash_tftp: flashbackup.tar.gz 10.17.84.225 flashbackup.tar.gz

CheckList_MD:
  - show: show clock
  - show: show version
  - show: show image version
  - show: show storage
  - show: show cpuload
  - show: show memory
  - show: show boot
  - show: show switches
  - show: show switchinfo
  - show: show boot history

  - show: show user
  - show: show ap database long 
  - show: show ap bss-table 
  - show: show ap essid
  - show: show ap active counters
  - show: show ap debug counters
  - show: show lc-cluster group-membership
  - show: show switches
  - show: show license
  - show: show running-config
  - show: show boot
  - show: show version
  #- backup_flash: flashbackup
  #- copy_flash_tftp: flashbackup.tar.gz 10.17.84.225 flashbackup.tar.gz
  

Authentication:
  username: admin
  password: Aruba@123$

Validate Image before upgrade: True
Validate controller sync before upgrade: True
Validate controller up before upgrade: True

tftp: 10.17.84.225

Pre_image_AP: True
max_ap_image_load: 10

