---
Upgrade:
  - hostname: ""
    device_type: MM
    host: ""

  - hostname: ""
    device_type: MD
    host: ""


default_settings:
  AOS_Source:
    device_type: ftp
    ftp_host: ""
    ftp_username: ""
    ftp_password: ""
    ftp_path: /

  MM:
    image_file_name: ""
    image_version: ""
    image_build: ""
    upgrade_disk: Auto
    CheckList:
      - show: show clock
      - show: show version
      - show: show image version
      - show: show storage
      - show: show cpuload
      - show: show memory
      - show: show boot
      - show: show switches
      - show: show switchinfo
      - show: show boot history

      - show: show crypto Ipsec sa
      - show: show master-redundancy
      - show: show database synchronize
      - show: show license
      - show: show running-config


  MD:
    image_file_name: ""
    image_version: ""
    image_build: ""
    upgrade_disk: Auto
    Pre_image_AP: True
    max_ap_image_load: 1
    CheckList:
      - show: show clock
      - show: show version
      - show: show image version
      - show: show storage
      - show: show cpuload
      - show: show memory
      - show: show boot
      - show: show switches
      - show: show switchinfo
      - show: show boot history

      - show: show user
      - show: show ap database long 
      - show: show ap bss-table 
      - show: show ap essid
      - show: show ap active counters
      - show: show ap debug counters
      - show: show lc-cluster group-membership
      - show: show switches
      - show: show license
      - show: show running-config
      - show: show boot
      - show: show version

  Authentication:
    username: ""
    password: ""


  Validate_Image_before_upgrade: True
  Validate_controller_sync_before_upgrade: True
  Validate_controller_up_before_upgrade: True
  Backup_flash_before_upgrade: True
  Backup_configuration_before_upgrade: True
  Backup_license_before_upgrade: True

