---
Upgrade:
  - hostname: NaaS-MM-1
    device_type: MM
    host: 10.17.84.220:4343

  - hostname: NaaS-VMC-1
    device_type: MD
    host: 10.17.84.221:4343


default_settings:
  AOS_Source:
    device_type: ftp
    ftp_host: 10.17.84.225
    ftp_username: admin
    ftp_password: admin123456
    ftp_path: /

  MM:
    image_file_name: ArubaOS_MM_8.6.0.5_75979
    image_version: 8.6.0.5
    image_build: "75979"
    upgrade_disk: Auto
    CheckList:
      - show: show clock
      - show: show version
      - show: show image version
      - show: show storage
      - show: show cpuload
      - show: show memory
      - show: show boot
      - show: show switches
      - show: show switchinfo
      - show: show boot history

      - show: show crypto Ipsec sa
      - show: show master-redundancy
      - show: show database synchronize
      - show: show license
      - show: show running-config


  MD:
    image_file_name: ArubaOS_VMC_8.6.0.5_75979
    image_version: 8.6.0.5
    image_build: "75979"
    upgrade_disk: Auto
    Pre_image_AP: True
    max_ap_image_load: 1
    CheckList:
      - show: show clock
      - show: show version
      - show: show image version
      - show: show storage
      - show: show cpuload
      - show: show memory
      - show: show boot
      - show: show switches
      - show: show switchinfo
      - show: show boot history

      - show: show user
      - show: show ap database long 
      - show: show ap bss-table 
      - show: show ap essid
      - show: show ap active counters
      - show: show ap debug counters
      - show: show lc-cluster group-membership
      - show: show switches
      - show: show license
      - show: show running-config
      - show: show boot
      - show: show version

  Authentication:
    username: admin
    password: Aruba@123$


  Validate_Image_before_upgrade: False
  Validate_controller_sync_before_upgrade: False
  Validate_controller_up_before_upgrade: False

